version: '3.3'

volumes:
  pg_data:
  static_value:
  media_value:

services:

  frontend:
    # image: serg163/foogram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    # image: serg163/foogram_backend
    build: 
      context: ../backend/
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "9080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
