# Generated by Django 4.2.3 on 2023-07-28 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_recipe_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shopping_card',
            field=models.ManyToManyField(related_name='shopping_recipes', to=settings.AUTH_USER_MODEL, verbose_name='В карточку покупок'),
        ),
    ]
