# Generated by Django 4.2.3 on 2023-07-28 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_recipe_shopping_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shopping_card',
            field=models.ManyToManyField(blank=True, related_name='shopping_recipes', to=settings.AUTH_USER_MODEL, verbose_name='В карточку покупок'),
        ),
    ]
