name: Main Foogram Workflow

on:
  [push]
    # branches:
    #   - develop
    #   - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Chek out code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.0.0 flake8-isort==6.0.0
        pip install -r backend/requirements.txt
    - name: Test wich flake8 and django test
      run: |
        python -m flake8 backend/
        pytest
        cd backend/ python manage.py test
        python manage.py test